CREATE TABLE "user" (
	user_id BIGSERIAL PRIMARY KEY,
	name VARCHAR(128) NOT NULL,
	original_name VARCHAR(128) NOT NULL,
	password VARCHAR(128) NOT NULL,
	email VARCHAR(256) NOT NULL,
	created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	status BOOLEAN NOT NULL DEFAULT true
);
